name: Weekly Movies Trigger

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  trigger-supabase-function:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Supabase Function
      env:
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        curl -L -X POST 'https://ybrwimxtjailumgoocni.supabase.co/functions/v1/get-weekly-serials' \
        -H 'Authorization: Bearer $SUPABASE_ANON_KEY' \
        --data '{"name":"Functions"}'
